// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hkllymgwmpebwdgrqaqh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhrbGx5bWd3bXBlYndkZ3JxYXFoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDU1OTMxNzYsImV4cCI6MjA2MTE2OTE3Nn0.R7KCUE4O1OSKrLiPxdxgxv0e0cW176iKQOK2sf7btdM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);